export const CREATE_SURVEY = "CREATE_SURVEY";
export const CREATE_SURVEY_SUCCESS = "CREATE_SURVEY_SUCCESS";
export const CHARTS_GET = "CHARTS_GET";
export const CHARTS_GET_SUCCESS = "CHARTS_GET_SUCCESS";
